name: Sync Template
on:
  # Runs every Monday at midnight (UTC)
  schedule:
    - cron: '0 0 * * 1'
  # Allows you to run this manually from the Actions tab
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # Necessary permissions to create a PR
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync with Template
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          # Replace with the template repo (e.g., 'username/repo')
          template_repo_path: DarekRepos/forty-astro-theme
          # This is the branch in your repo to receive updates
          target_branch: master